<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

+'<div id="container" class="box">'
+'<div id="wrap">'
+'<div id="container">'
+'<div id="content">'
+'<div class="index">'
+'<img src="resources/img/fare/top_menu_img_2.png" alt="이용요금을 알려드립니다.">'
+'</div>'
+'<div class="box">'
+'<div style="margin-top:30px;display:block;overflow:hidden;width:100%;">'
+'<a href="https://goo.gl/QFGQtZ"><img src="resources/img/fare/banner_20160530.jpg" alt=""></a>'
+'</div>'
+'<div class="group">'
+'<h3><img src="resources/img/fare/socarzone_drive_fee.png" alt="전국 쏘카존 대여요금 안내"></h3>'
+'<p><img src="resources/img/fare/rental_txt14.gif" alt="타면된다, 쏘카!​ 10분단위로 자유롭게 신나는 드라이빙을 즐기세요! 다양한 쿠폰혜택과 모바일에서만 만나볼 수 있는 특가상품까지 부담없이 누리세요!"></p>'
+'<table cellspacing="0" class="cols">'
+'<colgroup>'
+'<col width="82">'
+'<col width="172">'
+'<col width="90">'
+'<col width="90">'
+'<col width="90">'
+'<col width="110">'
+'<col>'
+'</colgroup>'
+'<thead>'
+'<tr>'
+'<th rowspan="2">차종</th>'
+'<th rowspan="2">모델</th>'
+'<th rowspan="2">기준 대여요금<br>(10분기준)</th>'
+'<th colspan="2">쏘친만을 위한 <span style="color:#f63325">특별할인!</span></th>'
+'<th rowspan="2">주행요금<br>(주행거리 Km당)</th>'
+'</tr>'
+'<tr>'
+'<th class="strong">주중</th>'
+'<th>주말</th>'
+'</tr>'
+'</thead>'
+'<tbody>'
+'<tr>'
+'<th rowspan="4" class="first">경형A<br></th>'
+'<td class="tal">모닝</td>'
+'<td>1,200원</td>'
+'<td class="strong">720원~</td>'
+'<td>960원~</td>'
+'<td>160원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">스파크</td>'
+'<td>1,200원</td>'
+'<td class="strong">720원~</td>'
+'<td>960원~</td>'
+'<td>160원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">넥스트스파크</td>'
+'<td>1,200원</td>'
+'<td class="strong">720원~</td>'
+'<td>960원~</td>'
+'<td>160원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">레이</td>'
+'<td>1,250원</td>'
+'<td class="strong">750원~</td>'
+'<td>1,000원~</td>'
+'<td>170원</td>'
+'</tr>'
+'<tr>'
+'<th rowspan="2" class="first">소형</th>'
+'<td class="tal">프라이드</td>'
+'<td>1,430원</td>'
+'<td class="strong">850원~</td>'
+'<td>1,140원~</td>'
+'<td>170원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">엑센트</td>'
+'<td>1,430원</td>'
+'<td class="strong">850원~</td>'
+'<td>1,140원~</td>'
+'<td>170원</td>'
+'</tr>'
+'<tr>'
+'<th rowspan="3" class="first">준중형</th>'
+'<td class="tal">K3</td>'
+'<td>1,580원</td>'
+'<td class="strong">950원~</td>'
+'<td>1,260원~</td>'
+'<td>170원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">아반떼</td>'
+'<td>1,580원</td>'
+'<td class="strong">950원~</td>'
+'<td>1,260원~</td>'
+'<td>170원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">아반떼AD</td>'
+'<td>1,580원</td>'
+'<td class="strong">950원~</td>'
+'<td>1,260원~</td>'
+'<td>170원</td>'
+'</tr>'
+'<tr>'
+'<th rowspan="5" class="first">중형</th>'
+'<td class="tal">K5(LPG)</td>'
+'<td>2,160원</td>'
+'<td class="strong">1,300원~</td>'
+'<td>1,730원~</td>'
+'<td>140원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">LF 쏘나타</td>'
+'<td>2,160원</td>'
+'<td class="strong">1,300원~</td>'
+'<td>1,730원~</td>'
+'<td>180원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">LF 쏘나타(LPG)</td>'
+'<td>2,160원</td>'
+'<td class="strong">1,300원~</td>'
+'<td>1,730원~</td>'
+'<td>140원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">SM5</td>'
+'<td>2,160원</td>'
+'<td class="strong">1,300원~</td>'
+'<td>1,730원~</td>'
+'<td>180원</td>'
+'</tr>'
+'<tr>'
+'<td class="tal">말리부</td>'
+'<td>2,660원</td>'
+'<td class="strong">1,600원~</td>'
+'<td>2,130원~</td>'
+'<td>180원</td>'
+'</tr>'
+'</tbody>'
+'</table>'
+'<br>'
+'<span style="color: #333">※ 주중/주말 기준</span>'
+'<br>'
+'<span style="color: #333">　·</span><span style="color: #333">주중 - 일 19:00 ~ 금 19:00 / 주중 심야 - 00:00 ~ 06:00</span>'
+'<br>'
+'<span style="color: #333">　·</span><span style="color: #333">주말 - 금 19:00 ~ 일 19:00 (공휴일 및 당사 지정 성수기 포함)</span>'
+'<ul><br>'
+'<li>요금표의 SO회원 특별할인 금액은 최저가 기준으로 지역마다 다를 수 있습니다.</li>'
+'<li>대여요금은 지역별, 성수기/비수기 등에 따라 탄력요금제로 운영하므로, 위에 안내된 요금은 결제 시 요금과 다를 수 있습니다.</li>'
+'<li>주행요금은 차량 이용 후 실제 주행거리에 따라 부과됩니다. 주행요금 계산기로 예상 비용을 미리 확인해보세요. <a href="#" class="oil">주행요금 계산기</a></li>'
+'<li>편도/D2D(도어 투 도어) 서비스 이용 시에는 차량 회송비용 등을 고려한 별도 요금이 추가 과금될 수 있습니다.</li>'
+'<li>대여요금 및 주행요금은 당사 내부정책/유가변동에 따라 변경될 수 있습니다.</li>'
+'</ul>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'