<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>


+'<div id="container" class="box">'
+'<div id="content">'
+'<div class="index">'
+'<img src="resources/img/guide/top_menu_img_1.png" alt="쏘카에 대해 알아볼까요?">'
+'</div>'
+'<div class="box1">'
+'<div class="snb">'
+'<ul class="menu">'
+'<li class="on"><a href="#socar1" class="menu1">이용방법</a></li>'
+'<li><a href="#socar2" class="menu2">이용규칙</a></li>'
+'<li><a href="#socar3" class="menu3">모바일 이용안내</a></li>'
+'<li><a href="#socar4" class="menu4">쏘카 가이드</a></li>'
+'<li><a href="#socar5" class="menu5">쏘카 임팩트</a></li>'
+'</ul>'
+'<ul class="banner">'
+'<li><a href="https://www.facebook.com/socarsharing" target="_blank"><img src="resources/img/guide/banner1.gif" alt="쏘카 페이스북"></a></li>'
+'<li><a href="http://blog.socar.kr" target="_blank"><img src="resources/img/guide/banner2_n.gif" alt="쏘카 블로그"></a></li>'
+'<li><a href="https://goo.gl/Aqsjr5" target="_blank"><img src="resources/img/guide/banner3.gif" alt="쏘카 인재채용"></a></li>'
+'</ul>'
+'</div>'
+'<div id="socar1" class="content">'
+'<h3><img src="resources/img/guide/txt10.gif" alt="쏘카 이용방법"></h3>'
+'<p class="txt"><img src="resources/img/guide/txt11.gif" alt="가입에서 예약 사용까지 간편하게 이용할 수 있는 편리하고 경제적인 쏘카의 이용방법을 알려드립니다. 쏘카와 함께 스마트 카셰어링을 경험해 보세요! "></p>'
+'<ul>'
+'<li class="rule1">'
+'<h4><img src="resources/img/guide/txt12.gif" alt="회원 가입"></h4>'
+'<p>카셰어링은 신뢰를 기반으로 한 회원제 서비스입니다.<br>'
+'운전면허 및 결제카드 등록 후 SO회원이 되시면 쏘카 이용이 가능합니다.</p>'
+'</li>'
+'<li class="rule2">'
+'<h4><img src="resources/img/guide/txt13.gif" alt="차량 예약"></h4>'
+'<p>SO회원 가입 승인 후 쏘카 예약이 가능합니다. 홈페이지 및 모바일앱을 이용해 예약하실<br>수 있고 정상적으로 예약완료된 경우 휴대폰으로 확인메시지가 전송됩니다.</p>'
+'<p>'
+'<img src="resources/img/guide/mobile.gif" alt="안드로이드폰, 아이폰" usemap="#mobile.gif">'
+'<map name="mobile.gif">'
+'<area shape="rect" coords="1,0,98,23" href="https://play.google.com/store/apps/details?id=socar.Socar&amp;utm_source=www-socar&amp;utm_medium=guide" target="_blank" alt="안드로이드폰">'
+'<area shape="rect" coords="99,0,166,23" href="https://itunes.apple.com/kr/app/id515173864" target="_blank" alt="아이폰">'
+'</map>'
+'</p>'
+'</li>'
+'<li class="rule3">'
+'<h4><img src="resources/img/guide/txt14.gif" alt="쏘카 이용"></h4>'
+'<p>쏘카앱 스마트키 잠금해제 버튼을 누르거나, 등록한 회원카드를 차량 앞 유리에 부착된 단말기에 접촉시켜 주세요. 경적음이 울린 후 차량 문이 열립니다.<br> 예약한 시간 동안에는 회원카드 및 모바일앱 스마트키로 차량 문을 제어할 수 있습니다.</p>'
+'</li>'
+'<li class="rule4">'
+'<h4><img src="resources/img/guide/txt15.gif" alt="차량 반납"></h4>'
+'<p>반납 시간에 맞추어 차량을 반납 장소에 주차하신 후 모바일앱 스마트키 및 회원카드로 차량 문을 <br>잠가 주세요.<br>'
+'제자리에 정상 반납 처리되면 휴대폰으로 확인 메시지가 발송됩니다.</p>'
+'</li>'
+'<li class="rule5">'
+'<h4><img src="resources/img/guide/txt16.gif" alt="요금 결제"></h4>'
+'<p>차량 이용에 따른 요금은 대여료와 주행요금으로 구분되며, 가입시 등록한 결제카드로 청구됩니다.<br>'
+'결제가 완료되지 않으면 차량 사용에 제한이 있을 수 있으니, 미리 결제카드의 유효여부를<br>확인해주세요. </p>'
+'</li>'
+'</ul>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
+'</div>'
